name: Dispatch Workflow with Parameters
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: master
            tag: v0.0.0
    steps:
      - name: Send Dispatch Event
        run: |
          curl -d '{"event_type":"run-tests","client_payload":{"branch":"${{ matrix.branch }}","tag":"${{ matrix.tag }}"}}' \
               -v -L -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.PAT }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               --fail-with-body \
               https://api.github.com/repos/krzysztof-gawrys-cognitran/promote-workflow/dispatches

      - name: Wait for Workflow to Complete
        run: |
          REPO="krzysztof-gawrys-cognitran/promote-workflow"
          WORKFLOW_NAME="promote.yml"
          STATUS="in_progress"
          RUN_ID=""

          echo "Waiting for workflow $WORKFLOW_NAME in $REPO..."

          while [[ "$STATUS" == "in_progress" || "$STATUS" == "queued" || -z "$STATUS" ]]; do
            sleep 10
            RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
                          "https://api.github.com/repos/$REPO/actions/runs?per_page=1" \
                          | jq -r '.workflow_runs[] | select(.name=="Run Tests with Parameters") | .id' | head -n 1)

            if [[ -z "$RUN_ID" ]]; then
              echo "No recent workflow run found, retrying..."
              continue
            fi

            STATUS=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
                          "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID" \
                          | jq -r '.status')

            echo "Workflow Status: $STATUS"
          done

          if [[ "$STATUS" != "completed" ]]; then
            echo "Workflow failed or was canceled!"
            exit 1
          fi

          echo "Workflow completed successfully!"
