name: Dispatch Workflow with Parameters
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/owner/other-repo/dispatches \
               -d '{"event_type": "run-tests", "client_payload": {"branch": "develop", "version": "1.2.3"}}'