name: Dispatch Workflow with Parameters
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event
        run: |
          curl -v -L -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.PAT }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               -X POST \
               -d '{"event_type":"run-tests","client_payload":{"unit":false,"integration":true}}' \
               https://api.github.com/repos/krzysztof-gawrys-cognitran/promote-workflow/dispatches
